// Code generated by MockGen. DO NOT EDIT.
// Source: client/interface.go
//
// Generated by this command:
//
//	mockgen -source=client/interface.go -destination=internal/testutil/mock_client.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	tokenv1 "github.com/aetomala/token-engine/gen/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// IssueToken mocks base method.
func (m *MockClient) IssueToken(ctx context.Context, req *tokenv1.IssueTokenRequest) (*tokenv1.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueToken", ctx, req)
	ret0, _ := ret[0].(*tokenv1.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueToken indicates an expected call of IssueToken.
func (mr *MockClientMockRecorder) IssueToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueToken", reflect.TypeOf((*MockClient)(nil).IssueToken), ctx, req)
}

// RefreshToken mocks base method.
func (m *MockClient) RefreshToken(ctx context.Context, req *tokenv1.RefreshTokenRequest) (*tokenv1.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, req)
	ret0, _ := ret[0].(*tokenv1.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockClientMockRecorder) RefreshToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockClient)(nil).RefreshToken), ctx, req)
}

// RevokeAllForAudience mocks base method.
func (m *MockClient) RevokeAllForAudience(ctx context.Context, req *tokenv1.RevokeAudienceRequest) (*tokenv1.RevokeTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForAudience", ctx, req)
	ret0, _ := ret[0].(*tokenv1.RevokeTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllForAudience indicates an expected call of RevokeAllForAudience.
func (mr *MockClientMockRecorder) RevokeAllForAudience(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForAudience", reflect.TypeOf((*MockClient)(nil).RevokeAllForAudience), ctx, req)
}

// RevokeAllForUserAndAudience mocks base method.
func (m *MockClient) RevokeAllForUserAndAudience(ctx context.Context, req *tokenv1.RevokeUserAndAudienceRequest) (*tokenv1.RevokeTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUserAndAudience", ctx, req)
	ret0, _ := ret[0].(*tokenv1.RevokeTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllForUserAndAudience indicates an expected call of RevokeAllForUserAndAudience.
func (mr *MockClientMockRecorder) RevokeAllForUserAndAudience(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUserAndAudience", reflect.TypeOf((*MockClient)(nil).RevokeAllForUserAndAudience), ctx, req)
}

// RevokeAllUserTokens mocks base method.
func (m *MockClient) RevokeAllUserTokens(ctx context.Context, req *tokenv1.RevokeUserRequest) (*tokenv1.RevokeTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserTokens", ctx, req)
	ret0, _ := ret[0].(*tokenv1.RevokeTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllUserTokens indicates an expected call of RevokeAllUserTokens.
func (mr *MockClientMockRecorder) RevokeAllUserTokens(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserTokens", reflect.TypeOf((*MockClient)(nil).RevokeAllUserTokens), ctx, req)
}

// RevokeToken mocks base method.
func (m *MockClient) RevokeToken(ctx context.Context, req *tokenv1.RevokeTokenRequest) (*tokenv1.RevokeTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, req)
	ret0, _ := ret[0].(*tokenv1.RevokeTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockClientMockRecorder) RevokeToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockClient)(nil).RevokeToken), ctx, req)
}
