// Code generated by MockGen. DO NOT EDIT.
// Source: internal/registry/tenant.go
//
// Generated by this command:
//
//	mockgen -source=internal/registry/tenant.go -destination=internal/testutil/mock_tenant_registry.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	tokens "github.com/aetomala/jwtauth/pkg/tokens"
	registry "github.com/aetomala/token-engine/internal/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantRegistry is a mock of TenantRegistry interface.
type MockTenantRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRegistryMockRecorder
	isgomock struct{}
}

// MockTenantRegistryMockRecorder is the mock recorder for MockTenantRegistry.
type MockTenantRegistryMockRecorder struct {
	mock *MockTenantRegistry
}

// NewMockTenantRegistry creates a new mock instance.
func NewMockTenantRegistry(ctrl *gomock.Controller) *MockTenantRegistry {
	mock := &MockTenantRegistry{ctrl: ctrl}
	mock.recorder = &MockTenantRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRegistry) EXPECT() *MockTenantRegistryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTenantRegistry) Add(ctx context.Context, tenantID string, cfg registry.TenantConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, tenantID, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockTenantRegistryMockRecorder) Add(ctx, tenantID, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTenantRegistry)(nil).Add), ctx, tenantID, cfg)
}

// Drain mocks base method.
func (m *MockTenantRegistry) Drain(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drain", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Drain indicates an expected call of Drain.
func (mr *MockTenantRegistryMockRecorder) Drain(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drain", reflect.TypeOf((*MockTenantRegistry)(nil).Drain), ctx, tenantID)
}

// Get mocks base method.
func (m *MockTenantRegistry) Get(ctx context.Context, tenantID string) (tokens.TokenManager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tenantID)
	ret0, _ := ret[0].(tokens.TokenManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTenantRegistryMockRecorder) Get(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTenantRegistry)(nil).Get), ctx, tenantID)
}

// Remove mocks base method.
func (m *MockTenantRegistry) Remove(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockTenantRegistryMockRecorder) Remove(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockTenantRegistry)(nil).Remove), ctx, tenantID)
}
