// Code generated by MockGen. DO NOT EDIT.
// Source: internal/registry/multi_tenant.go
//
// Generated by this command:
//
//	mockgen -source=internal/registry/multi_tenant.go -destination=internal/testutil/mock_expiry_index_backfiller.go -package=testutil -mock_names=ExpiryIndexBackfiller=MockExpiryIndexBackfiller
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExpiryIndexBackfiller is a mock of ExpiryIndexBackfiller interface.
type MockExpiryIndexBackfiller struct {
	ctrl     *gomock.Controller
	recorder *MockExpiryIndexBackfillerMockRecorder
	isgomock struct{}
}

// MockExpiryIndexBackfillerMockRecorder is the mock recorder for MockExpiryIndexBackfiller.
type MockExpiryIndexBackfillerMockRecorder struct {
	mock *MockExpiryIndexBackfiller
}

// NewMockExpiryIndexBackfiller creates a new mock instance.
func NewMockExpiryIndexBackfiller(ctrl *gomock.Controller) *MockExpiryIndexBackfiller {
	mock := &MockExpiryIndexBackfiller{ctrl: ctrl}
	mock.recorder = &MockExpiryIndexBackfillerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpiryIndexBackfiller) EXPECT() *MockExpiryIndexBackfillerMockRecorder {
	return m.recorder
}

// BackfillExpiryIndex mocks base method.
func (m *MockExpiryIndexBackfiller) BackfillExpiryIndex(ctx context.Context) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillExpiryIndex", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BackfillExpiryIndex indicates an expected call of BackfillExpiryIndex.
func (mr *MockExpiryIndexBackfillerMockRecorder) BackfillExpiryIndex(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillExpiryIndex", reflect.TypeOf((*MockExpiryIndexBackfiller)(nil).BackfillExpiryIndex), ctx)
}
