// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aetomala/go/pkg/mod/github.com/aetomala/jwtauth@v1.0.0/pkg/tokens/interface.go
//
// Generated by this command:
//
//	mockgen -source=/Users/aetomala/go/pkg/mod/github.com/aetomala/jwtauth@v1.0.0/pkg/tokens/interface.go -destination=internal/testutil/mock_tokens_manager.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	storage "github.com/aetomala/jwtauth/pkg/storage"
	tokens "github.com/aetomala/jwtauth/pkg/tokens"
	jwt "github.com/golang-jwt/jwt/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenManager is a mock of TokenManager interface.
type MockTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerMockRecorder
	isgomock struct{}
}

// MockTokenManagerMockRecorder is the mock recorder for MockTokenManager.
type MockTokenManagerMockRecorder struct {
	mock *MockTokenManager
}

// NewMockTokenManager creates a new mock instance.
func NewMockTokenManager(ctrl *gomock.Controller) *MockTokenManager {
	mock := &MockTokenManager{ctrl: ctrl}
	mock.recorder = &MockTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManager) EXPECT() *MockTokenManagerMockRecorder {
	return m.recorder
}

// CleanupExpiredTokens mocks base method.
func (m *MockTokenManager) CleanupExpiredTokens(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredTokens", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredTokens indicates an expected call of CleanupExpiredTokens.
func (mr *MockTokenManagerMockRecorder) CleanupExpiredTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredTokens", reflect.TypeOf((*MockTokenManager)(nil).CleanupExpiredTokens), ctx)
}

// IntrospectToken mocks base method.
func (m *MockTokenManager) IntrospectToken(ctx context.Context, token string) (*tokens.TokenMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntrospectToken", ctx, token)
	ret0, _ := ret[0].(*tokens.TokenMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntrospectToken indicates an expected call of IntrospectToken.
func (mr *MockTokenManagerMockRecorder) IntrospectToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntrospectToken", reflect.TypeOf((*MockTokenManager)(nil).IntrospectToken), ctx, token)
}

// IssueAccessToken mocks base method.
func (m *MockTokenManager) IssueAccessToken(ctx context.Context, userID string, opts ...tokens.IssueOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IssueAccessToken", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessToken indicates an expected call of IssueAccessToken.
func (mr *MockTokenManagerMockRecorder) IssueAccessToken(ctx, userID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessToken", reflect.TypeOf((*MockTokenManager)(nil).IssueAccessToken), varargs...)
}

// IssueAccessTokenWithClaims mocks base method.
func (m *MockTokenManager) IssueAccessTokenWithClaims(ctx context.Context, userID string, claims tokens.CustomClaims, opts ...tokens.IssueOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userID, claims}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IssueAccessTokenWithClaims", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessTokenWithClaims indicates an expected call of IssueAccessTokenWithClaims.
func (mr *MockTokenManagerMockRecorder) IssueAccessTokenWithClaims(ctx, userID, claims any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userID, claims}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessTokenWithClaims", reflect.TypeOf((*MockTokenManager)(nil).IssueAccessTokenWithClaims), varargs...)
}

// IssueRefreshToken mocks base method.
func (m *MockTokenManager) IssueRefreshToken(ctx context.Context, userID string, opts ...tokens.IssueOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IssueRefreshToken", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueRefreshToken indicates an expected call of IssueRefreshToken.
func (mr *MockTokenManagerMockRecorder) IssueRefreshToken(ctx, userID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueRefreshToken", reflect.TypeOf((*MockTokenManager)(nil).IssueRefreshToken), varargs...)
}

// IssueRefreshTokenWithClaims mocks base method.
func (m *MockTokenManager) IssueRefreshTokenWithClaims(ctx context.Context, userID string, claims tokens.CustomClaims, opts ...tokens.IssueOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userID, claims}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IssueRefreshTokenWithClaims", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueRefreshTokenWithClaims indicates an expected call of IssueRefreshTokenWithClaims.
func (mr *MockTokenManagerMockRecorder) IssueRefreshTokenWithClaims(ctx, userID, claims any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userID, claims}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueRefreshTokenWithClaims", reflect.TypeOf((*MockTokenManager)(nil).IssueRefreshTokenWithClaims), varargs...)
}

// IssueTokenPair mocks base method.
func (m *MockTokenManager) IssueTokenPair(ctx context.Context, userID string, opts ...tokens.IssueOption) (string, string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IssueTokenPair", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueTokenPair indicates an expected call of IssueTokenPair.
func (mr *MockTokenManagerMockRecorder) IssueTokenPair(ctx, userID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokenPair", reflect.TypeOf((*MockTokenManager)(nil).IssueTokenPair), varargs...)
}

// IssueTokenPairWithClaims mocks base method.
func (m *MockTokenManager) IssueTokenPairWithClaims(ctx context.Context, userID string, accessClaims, refreshClaims tokens.CustomClaims, opts ...tokens.IssueOption) (string, string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userID, accessClaims, refreshClaims}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IssueTokenPairWithClaims", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueTokenPairWithClaims indicates an expected call of IssueTokenPairWithClaims.
func (mr *MockTokenManagerMockRecorder) IssueTokenPairWithClaims(ctx, userID, accessClaims, refreshClaims any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userID, accessClaims, refreshClaims}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokenPairWithClaims", reflect.TypeOf((*MockTokenManager)(nil).IssueTokenPairWithClaims), varargs...)
}

// ListTokens mocks base method.
func (m *MockTokenManager) ListTokens(ctx context.Context, cursor string, count int) ([]*storage.RefreshToken, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokens", ctx, cursor, count)
	ret0, _ := ret[0].([]*storage.RefreshToken)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTokens indicates an expected call of ListTokens.
func (mr *MockTokenManagerMockRecorder) ListTokens(ctx, cursor, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*MockTokenManager)(nil).ListTokens), ctx, cursor, count)
}

// ListTokensForAudience mocks base method.
func (m *MockTokenManager) ListTokensForAudience(ctx context.Context, audience, cursor string, count int) ([]*storage.RefreshToken, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokensForAudience", ctx, audience, cursor, count)
	ret0, _ := ret[0].([]*storage.RefreshToken)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTokensForAudience indicates an expected call of ListTokensForAudience.
func (mr *MockTokenManagerMockRecorder) ListTokensForAudience(ctx, audience, cursor, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokensForAudience", reflect.TypeOf((*MockTokenManager)(nil).ListTokensForAudience), ctx, audience, cursor, count)
}

// ListTokensForUser mocks base method.
func (m *MockTokenManager) ListTokensForUser(ctx context.Context, userID, cursor string, count int) ([]*storage.RefreshToken, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokensForUser", ctx, userID, cursor, count)
	ret0, _ := ret[0].([]*storage.RefreshToken)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTokensForUser indicates an expected call of ListTokensForUser.
func (mr *MockTokenManagerMockRecorder) ListTokensForUser(ctx, userID, cursor, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokensForUser", reflect.TypeOf((*MockTokenManager)(nil).ListTokensForUser), ctx, userID, cursor, count)
}

// RefreshAccessToken mocks base method.
func (m *MockTokenManager) RefreshAccessToken(ctx context.Context, refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAccessToken", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshAccessToken indicates an expected call of RefreshAccessToken.
func (mr *MockTokenManagerMockRecorder) RefreshAccessToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAccessToken", reflect.TypeOf((*MockTokenManager)(nil).RefreshAccessToken), ctx, refreshToken)
}

// RefreshAccessTokenWithClaims mocks base method.
func (m *MockTokenManager) RefreshAccessTokenWithClaims(ctx context.Context, refreshToken string, claims tokens.CustomClaims) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAccessTokenWithClaims", ctx, refreshToken, claims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshAccessTokenWithClaims indicates an expected call of RefreshAccessTokenWithClaims.
func (mr *MockTokenManagerMockRecorder) RefreshAccessTokenWithClaims(ctx, refreshToken, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAccessTokenWithClaims", reflect.TypeOf((*MockTokenManager)(nil).RefreshAccessTokenWithClaims), ctx, refreshToken, claims)
}

// RevokeAllForAudience mocks base method.
func (m *MockTokenManager) RevokeAllForAudience(ctx context.Context, audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForAudience", ctx, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForAudience indicates an expected call of RevokeAllForAudience.
func (mr *MockTokenManagerMockRecorder) RevokeAllForAudience(ctx, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForAudience", reflect.TypeOf((*MockTokenManager)(nil).RevokeAllForAudience), ctx, audience)
}

// RevokeAllForUserAndAudience mocks base method.
func (m *MockTokenManager) RevokeAllForUserAndAudience(ctx context.Context, userID, audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUserAndAudience", ctx, userID, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUserAndAudience indicates an expected call of RevokeAllForUserAndAudience.
func (mr *MockTokenManagerMockRecorder) RevokeAllForUserAndAudience(ctx, userID, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUserAndAudience", reflect.TypeOf((*MockTokenManager)(nil).RevokeAllForUserAndAudience), ctx, userID, audience)
}

// RevokeAllUserTokens mocks base method.
func (m *MockTokenManager) RevokeAllUserTokens(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserTokens indicates an expected call of RevokeAllUserTokens.
func (mr *MockTokenManagerMockRecorder) RevokeAllUserTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserTokens", reflect.TypeOf((*MockTokenManager)(nil).RevokeAllUserTokens), ctx, userID)
}

// RevokeRefreshToken mocks base method.
func (m *MockTokenManager) RevokeRefreshToken(ctx context.Context, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockTokenManagerMockRecorder) RevokeRefreshToken(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockTokenManager)(nil).RevokeRefreshToken), ctx, tokenID)
}

// ValidateAccessToken mocks base method.
func (m *MockTokenManager) ValidateAccessToken(ctx context.Context, tokenString string) (*jwt.RegisteredClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", ctx, tokenString)
	ret0, _ := ret[0].(*jwt.RegisteredClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenManagerMockRecorder) ValidateAccessToken(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenManager)(nil).ValidateAccessToken), ctx, tokenString)
}

// ValidateAccessTokenWithClaims mocks base method.
func (m *MockTokenManager) ValidateAccessTokenWithClaims(ctx context.Context, tokenString string) (*jwt.RegisteredClaims, map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessTokenWithClaims", ctx, tokenString)
	ret0, _ := ret[0].(*jwt.RegisteredClaims)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateAccessTokenWithClaims indicates an expected call of ValidateAccessTokenWithClaims.
func (mr *MockTokenManagerMockRecorder) ValidateAccessTokenWithClaims(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessTokenWithClaims", reflect.TypeOf((*MockTokenManager)(nil).ValidateAccessTokenWithClaims), ctx, tokenString)
}
