// Code generated by MockGen. DO NOT EDIT.
// Source: internal/health/health.go
//
// Generated by this command:
//
//	mockgen -source=internal/health/health.go -destination=internal/testutil/mock_reconciler_status.go -package=testutil -mock_names=ReconcilerStatus=MockReconcilerStatus
//

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockReconcilerStatus is a mock of ReconcilerStatus interface.
type MockReconcilerStatus struct {
	ctrl     *gomock.Controller
	recorder *MockReconcilerStatusMockRecorder
	isgomock struct{}
}

// MockReconcilerStatusMockRecorder is the mock recorder for MockReconcilerStatus.
type MockReconcilerStatusMockRecorder struct {
	mock *MockReconcilerStatus
}

// NewMockReconcilerStatus creates a new mock instance.
func NewMockReconcilerStatus(ctrl *gomock.Controller) *MockReconcilerStatus {
	mock := &MockReconcilerStatus{ctrl: ctrl}
	mock.recorder = &MockReconcilerStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconcilerStatus) EXPECT() *MockReconcilerStatusMockRecorder {
	return m.recorder
}

// LastSuccessAt mocks base method.
func (m *MockReconcilerStatus) LastSuccessAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastSuccessAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// LastSuccessAt indicates an expected call of LastSuccessAt.
func (mr *MockReconcilerStatusMockRecorder) LastSuccessAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastSuccessAt", reflect.TypeOf((*MockReconcilerStatus)(nil).LastSuccessAt))
}
