// Code generated by MockGen. DO NOT EDIT.
// Source: internal/registry/caller.go
//
// Generated by this command:
//
//	mockgen -source=internal/registry/caller.go -destination=internal/testutil/mock_caller_registry.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCallerRegistry is a mock of CallerRegistry interface.
type MockCallerRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockCallerRegistryMockRecorder
	isgomock struct{}
}

// MockCallerRegistryMockRecorder is the mock recorder for MockCallerRegistry.
type MockCallerRegistryMockRecorder struct {
	mock *MockCallerRegistry
}

// NewMockCallerRegistry creates a new mock instance.
func NewMockCallerRegistry(ctrl *gomock.Controller) *MockCallerRegistry {
	mock := &MockCallerRegistry{ctrl: ctrl}
	mock.recorder = &MockCallerRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallerRegistry) EXPECT() *MockCallerRegistryMockRecorder {
	return m.recorder
}

// IsPermitted mocks base method.
func (m *MockCallerRegistry) IsPermitted(ctx context.Context, callerIdentity, tenantID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPermitted", ctx, callerIdentity, tenantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPermitted indicates an expected call of IsPermitted.
func (mr *MockCallerRegistryMockRecorder) IsPermitted(ctx, callerIdentity, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPermitted", reflect.TypeOf((*MockCallerRegistry)(nil).IsPermitted), ctx, callerIdentity, tenantID)
}
