// Code generated by MockGen. DO NOT EDIT.
// Source: internal/audit/store.go
//
// Generated by this command:
//
//	mockgen -source=internal/audit/store.go -destination=internal/testutil/mock_audit.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	audit "github.com/aetomala/token-engine/internal/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockStore) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStoreMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStore)(nil).Ping), ctx)
}

// RecordRevocation mocks base method.
func (m *MockStore) RecordRevocation(ctx context.Context, event audit.RevocationEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRevocation", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRevocation indicates an expected call of RecordRevocation.
func (mr *MockStoreMockRecorder) RecordRevocation(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRevocation", reflect.TypeOf((*MockStore)(nil).RecordRevocation), ctx, event)
}
