// Code generated by MockGen. DO NOT EDIT.
// Source: internal/observability/metrics.go
//
// Generated by this command:
//
//	mockgen -source=internal/observability/metrics.go -destination=internal/testutil/mock_metrics.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// AddCounter mocks base method.
func (m *MockMetrics) AddCounter(name string, value float64, labels map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCounter", name, value, labels)
}

// AddCounter indicates an expected call of AddCounter.
func (mr *MockMetricsMockRecorder) AddCounter(name, value, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounter", reflect.TypeOf((*MockMetrics)(nil).AddCounter), name, value, labels)
}

// IncrementCounter mocks base method.
func (m *MockMetrics) IncrementCounter(name string, labels map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementCounter", name, labels)
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockMetricsMockRecorder) IncrementCounter(name, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockMetrics)(nil).IncrementCounter), name, labels)
}

// RecordDuration mocks base method.
func (m *MockMetrics) RecordDuration(name string, d time.Duration, labels map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDuration", name, d, labels)
}

// RecordDuration indicates an expected call of RecordDuration.
func (mr *MockMetricsMockRecorder) RecordDuration(name, d, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDuration", reflect.TypeOf((*MockMetrics)(nil).RecordDuration), name, d, labels)
}

// RecordHistogram mocks base method.
func (m *MockMetrics) RecordHistogram(name string, value float64, labels map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordHistogram", name, value, labels)
}

// RecordHistogram indicates an expected call of RecordHistogram.
func (mr *MockMetricsMockRecorder) RecordHistogram(name, value, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHistogram", reflect.TypeOf((*MockMetrics)(nil).RecordHistogram), name, value, labels)
}

// SetGauge mocks base method.
func (m *MockMetrics) SetGauge(name string, value float64, labels map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGauge", name, value, labels)
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockMetricsMockRecorder) SetGauge(name, value, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockMetrics)(nil).SetGauge), name, value, labels)
}
