// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aetomala/go/pkg/mod/github.com/aetomala/jwtauth@v1.0.0/pkg/keys/interface.go
//
// Generated by this command:
//
//	mockgen -source=/Users/aetomala/go/pkg/mod/github.com/aetomala/jwtauth@v1.0.0/pkg/keys/interface.go -destination=internal/testutil/mock_key_manager.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	rsa "crypto/rsa"
	reflect "reflect"

	keys "github.com/aetomala/jwtauth/pkg/keys"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyManager is a mock of KeyManager interface.
type MockKeyManager struct {
	ctrl     *gomock.Controller
	recorder *MockKeyManagerMockRecorder
	isgomock struct{}
}

// MockKeyManagerMockRecorder is the mock recorder for MockKeyManager.
type MockKeyManagerMockRecorder struct {
	mock *MockKeyManager
}

// NewMockKeyManager creates a new mock instance.
func NewMockKeyManager(ctrl *gomock.Controller) *MockKeyManager {
	mock := &MockKeyManager{ctrl: ctrl}
	mock.recorder = &MockKeyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyManager) EXPECT() *MockKeyManagerMockRecorder {
	return m.recorder
}

// GetAllKeyInfo mocks base method.
func (m *MockKeyManager) GetAllKeyInfo(ctx context.Context) ([]keys.KeyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllKeyInfo", ctx)
	ret0, _ := ret[0].([]keys.KeyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllKeyInfo indicates an expected call of GetAllKeyInfo.
func (mr *MockKeyManagerMockRecorder) GetAllKeyInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllKeyInfo", reflect.TypeOf((*MockKeyManager)(nil).GetAllKeyInfo), ctx)
}

// GetCurrentKeyInfo mocks base method.
func (m *MockKeyManager) GetCurrentKeyInfo(ctx context.Context) (*keys.KeyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentKeyInfo", ctx)
	ret0, _ := ret[0].(*keys.KeyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentKeyInfo indicates an expected call of GetCurrentKeyInfo.
func (mr *MockKeyManagerMockRecorder) GetCurrentKeyInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentKeyInfo", reflect.TypeOf((*MockKeyManager)(nil).GetCurrentKeyInfo), ctx)
}

// GetCurrentSigningKey mocks base method.
func (m *MockKeyManager) GetCurrentSigningKey(ctx context.Context) (*rsa.PrivateKey, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentSigningKey", ctx)
	ret0, _ := ret[0].(*rsa.PrivateKey)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCurrentSigningKey indicates an expected call of GetCurrentSigningKey.
func (mr *MockKeyManagerMockRecorder) GetCurrentSigningKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentSigningKey", reflect.TypeOf((*MockKeyManager)(nil).GetCurrentSigningKey), ctx)
}

// GetJWKS mocks base method.
func (m *MockKeyManager) GetJWKS(ctx context.Context) (*keys.JWKS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWKS", ctx)
	ret0, _ := ret[0].(*keys.JWKS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJWKS indicates an expected call of GetJWKS.
func (mr *MockKeyManagerMockRecorder) GetJWKS(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWKS", reflect.TypeOf((*MockKeyManager)(nil).GetJWKS), ctx)
}

// GetKeyInfo mocks base method.
func (m *MockKeyManager) GetKeyInfo(ctx context.Context, keyID string) (*keys.KeyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyInfo", ctx, keyID)
	ret0, _ := ret[0].(*keys.KeyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyInfo indicates an expected call of GetKeyInfo.
func (mr *MockKeyManagerMockRecorder) GetKeyInfo(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyInfo", reflect.TypeOf((*MockKeyManager)(nil).GetKeyInfo), ctx, keyID)
}

// GetPublicKey mocks base method.
func (m *MockKeyManager) GetPublicKey(ctx context.Context, keyID string) (*rsa.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKey", ctx, keyID)
	ret0, _ := ret[0].(*rsa.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockKeyManagerMockRecorder) GetPublicKey(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockKeyManager)(nil).GetPublicKey), ctx, keyID)
}

// IsRunning mocks base method.
func (m *MockKeyManager) IsRunning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockKeyManagerMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockKeyManager)(nil).IsRunning))
}

// RotateKeys mocks base method.
func (m *MockKeyManager) RotateKeys(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateKeys", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateKeys indicates an expected call of RotateKeys.
func (mr *MockKeyManagerMockRecorder) RotateKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateKeys", reflect.TypeOf((*MockKeyManager)(nil).RotateKeys), ctx)
}

// Shutdown mocks base method.
func (m *MockKeyManager) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockKeyManagerMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockKeyManager)(nil).Shutdown), ctx)
}

// Start mocks base method.
func (m *MockKeyManager) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockKeyManagerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockKeyManager)(nil).Start), ctx)
}
