// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/idempotency.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/idempotency.go -destination=internal/testutil/mock_idempotency_store.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdempotencyStore is a mock of IdempotencyStore interface.
type MockIdempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyStoreMockRecorder
	isgomock struct{}
}

// MockIdempotencyStoreMockRecorder is the mock recorder for MockIdempotencyStore.
type MockIdempotencyStoreMockRecorder struct {
	mock *MockIdempotencyStore
}

// NewMockIdempotencyStore creates a new mock instance.
func NewMockIdempotencyStore(ctrl *gomock.Controller) *MockIdempotencyStore {
	mock := &MockIdempotencyStore{ctrl: ctrl}
	mock.recorder = &MockIdempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyStore) EXPECT() *MockIdempotencyStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIdempotencyStore) Get(ctx context.Context, key string) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockIdempotencyStoreMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIdempotencyStore)(nil).Get), ctx, key)
}

// SetNX mocks base method.
func (m *MockIdempotencyStore) SetNX(ctx context.Context, key string, value []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNX", ctx, key, value)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNX indicates an expected call of SetNX.
func (mr *MockIdempotencyStoreMockRecorder) SetNX(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNX", reflect.TypeOf((*MockIdempotencyStore)(nil).SetNX), ctx, key, value)
}
